puts "Bootstrapping classes..."

require "maglev-database-explorer/database_views/globals"
require "maglev-database-explorer/database_views/object"
require "maglev-database-explorer/database_views/exception"
require "maglev-database-explorer/database_views/module"
require "maglev-database-explorer/database_views/array"
require "maglev-database-explorer/database_views/fixnum"
require "maglev-database-explorer/database_views/float"
require "maglev-database-explorer/database_views/string"
require "maglev-database-explorer/database_views/nilclass"
require "maglev-database-explorer/database_views/gsnmethod"
require "maglev-database-explorer/database_views/thread"
require "maglev-database-explorer/database_views/smalltalk_classes"
require "maglev-database-explorer/database_views/class"
require "maglev-database-explorer/database_views/execblock"
require "maglev-database-explorer/database_views/proc"
require "maglev-database-explorer/database_views/abstract_exception"
require "maglev-database-explorer/database_views/boolean"
require "maglev-database-explorer/database_views/abstract_dictionary"
require "maglev-database-explorer/database_views/hash"
require "maglev-database-explorer/database_views/system"
require "maglev-database-explorer/database_views/ruby_workspace"
require "maglev-database-explorer/database_views/repository"
require "maglev-database-explorer/database_views/maglev_record"

puts "Done bootstrapping classes."

